### ISSUE TITLE
Class selection UI needs rework

### ISSUE THREAD

**Issue by GingerAdonis** [JarnoVgr/ZombieSurvival#12]
It barely shows any info (only the tooltip). Could use a design upgrade and show more details about the classes and the gamemode basics.

**Comment by Dubyx** [comment]
I'll have a chat with Ben and come up with a design which looks unique. I want to avoid it looking like the old ZS menu. We are creating a new ZS game mode, not updating it from the old version.

**Comment by Dubyx** [comment]
I have resolved this and have created a Loadout menu which I feel is clean, concise, interesting and obviously has room for improvement.

**Comment by Dubyx** [comment]
This has been completed and the class menu is bug free and works correctly. It shows each class clearly, with what the classes load out is, and a description. Closing this ticket.
