### ISSUE TITLE
Zombie crosshair looks stretched

### ISSUE THREAD

**Issue by GingerAdonis** [JarnoVgr/ZombieSurvival#13]
![hl2 2016-02-26 16-12-47-13](https://cloud.githubusercontent.com/assets/2751672/13356077/d9756444-dca3-11e5-9f38-df6baa6aaaba.png)

**Comment by Dubyx** [comment]
Will fix, its using a bodge fix, will scale it properly and clean up code.

**Comment by Dubyx** [comment]
Fixed
