### ISSUE TITLE
Consider renaming SkillPoints to XP

### ISSUE THREAD

**Issue by GingerAdonis** [JarnoVgr/ZombieSurvival#18]
When looking at the HUD it shows 'x SkillPoints', which is, in my opinion, too much text. It can be changed to 'SP', but new players may not know what that is. While 'XP' (Experience Points) is more common and short as well.

**Comment by Dubyx** [comment]
I think XP would be too relatable to levelling, but SP would work. We can use that and then use 'SkillPoints' in the gun shop for people to understand its abbreviation. Thoughts?

**Comment by GingerAdonis** [comment]
Yeah true that. Shortening SkillPoints to 'SP' where possible is fine with me.

**Comment by Dubyx** [comment]
I will do that tonight :)

**Comment by Dubyx** [comment]
Done, closing this ticket.
