### ISSUE TITLE
SkillPoints text is over health bar?

### ISSUE THREAD

**Issue by GingerAdonis** [JarnoVgr/ZombieSurvival#20]
It looks like SP text is over the health bar, while the health text is to the left of it. Doesn't make any sense to me. Health should be together, and SP separate.

**Comment by Dubyx** [comment]
It was designed to be a health bar, but no longer serves a purpose. But I can code it to be a health bar, and then place the SP on a different section of the hud. 

Such as another box above it.

**Comment by GingerAdonis** [comment]
Maybe you should ook at the HL2 HUD. It's simple, which is nice.
You could indeed put SP in a separate box on top of it, or to the right. (latter has my preference)

**Comment by Dubyx** [comment]
What do you think about this? 

http://images.akamai.steamusercontent.com/ugc/262709962023023417/4F0F95F5F7BDEB11266670C6D04CD6D30A64B9FD/

**Comment by Dubyx** [comment]
Redoing the whole Human HUD.

**Comment by Dubyx** [comment]
Here we go, what do you think?

http://images.akamai.steamusercontent.com/ugc/262709962043327379/0C799A9E27EA72473CF736EE14CAD5EB6E2FDCCB/

**Comment by Dubyx** [comment]
Updated 

http://images.akamai.steamusercontent.com/ugc/262710441116323083/C873D9B380AE57CE514D596CBC932A6A2C0E0CBC/

**Comment by GingerAdonis** [comment]
Looks better!
- GC and SP values aren't aligned the same.
- Why not give a color to the healthbar, depending on the health? And make it blink when it's very low. (like the old ZS maybe?)
- Is there a reason to show the weapon name in the bottom right? If it has to be done, make it smaller and give it a panel (black background), just like the other HUD elements.
- Maybe move GCs to a different panel in the top-left? GCs aren't related/important to the current game while SP is.

**Comment by Dubyx** [comment]
-The health bar changes colour depending on the HP percentage, its just white at 100 HP
-I'll remove GC until its implemented
-The labels are only for tools which aren't clear to what it is. So the Hammer doesn't have it. But the Blow Torch does as a player may not know what it is. 
-I'll add a black rounded panel like the rest of the HUD items

Do you like this HUD design?

**Comment by GingerAdonis** [comment]
All good to me. :)

**Comment by Dubyx** [comment]
Can I close this ticket now xD 

http://images.akamai.steamusercontent.com/ugc/262710528773168912/A0EDE364E125E3816BC21D11507B26C6BA1AD024/

**Comment by GingerAdonis** [comment]
One minor thing: '0 SP' instead of 'SP: 0'. Improves readability

**Comment by Dubyx** [comment]
Ok so that is the last thing? Or is there anything else? :o

**Comment by GingerAdonis** [comment]
I always have something to bitch about. But for now it's all good! :)

**Comment by Dubyx** [comment]
Ok done, closing issue.

http://images.akamai.steamusercontent.com/ugc/262710528773215870/C9698930D884B7C04D220F9B428AA97C086DBD83/
