### ISSUE TITLE
Issues based on latest test

### ISSUE THREAD

**Issue by GingerAdonis** [JarnoVgr/ZombieSurvival#21]
Had a short gameplay. While I can't really tell if the gameplay is good (I'm a noob gameplay-wise), it does feel good. And it feels nice to play ZS again!
Here's a huge list of shit that felt wrong/odd or make no sense. etc.
I have taken some screenshots, so if something doesn't make sense to you. Just hit me up and I'll explain the specific issue.

LOADOUT/HUMAN CLASS SCREEN
- Server title isn't aligned properly.
- Server title should be "Mr. Green" instead of "Mr.Green". Maybe make a better logo? Use Akbar font for Zombie Survival part, like the loading screen?
- I'm unable to select other classes. Even double-clicking isn't working.
- If there's a time-limit to the loadoutscreen. Why am I not seeing it?
- Explain that it actually is a class screen.

HUD/UI
- Health and healthbar aren't aligned properly (vertically).
- Font size is on 2560x1440 too small, or the panels too big.
- If possible: Merge Player Model and Player Color windows.
- Credits window looks different than, for example, the options window.
- F3 menu just states 'Zombie Survival'. While that doesn't explain anything about the menu I'm looking at. "Game Menu" would be better.
- F3 should be toggle-able so if someone presses it accidently, it can be closed again
- Zombie HUD health text misses "+" which the human HUD does have.
- There are too many zombie classes. It confuses me. Maybe transform some into bosses?
- Zombie classes menu can't be closed without selecting a class. Toggle-ing F3 key doesn't work.
- SP HUD had an odd 1px width (full height) spacing on the right. So the panel isn't "full".
- Chat isn't working at intermission and vote screens.
- Voting screen needs work. Less derma/UI panels.

SWEPS
- Mobile supplies can only be placed when being crouched.
- When placed: Mobile supplies text looks crap.

GAME WHILE HUMAN
- Using Mobile Supplies while game isn't started yet should give a warning. Instead it does nothing.
- Is it possible to limit the sentry laser distance? It looks horrible if you see the laser going across the map.

GAME WHILE ZOMBIE
- Can we really try to get rid of the original zombie sound? It's horrible and hurts my ears. Is there a reason to keep 'em?

GAME
- Why do some players have a circle underneath them, and other's dont?
- The random unexplained slowdowns are annoying.

MISC
- RTD seems to be acting odd: "WIN: WIN: Ywa rolled the dice and gained 46KG of flesh!! rolled the dice and gained 46KG of flesh!!"

**Comment by Dubyx** [comment]
The screenshot of your screen res would be great. Obviously my monitor is only goes up to 1920x1080 :)

**Comment by GingerAdonis** [comment]
![20160518210512_1](https://cloud.githubusercontent.com/assets/2751672/15427985/11fbd668-1e99-11e6-86bf-7e486dd70f58.jpg)

**Comment by Dubyx** [comment]
Done
