### ISSUE TITLE
Improve scoreboard

### ISSUE THREAD

**Issue by GingerAdonis** [JarnoVgr/ZombieSurvival#6]
Would nice to make it look a bit more like the original.

**Comment by Dubyx** [comment]
Hmm ok, I can do that, shouldn't be too hard I don't think, Derma is rather easy to work with.

**Comment by Dubyx** [comment]
I have heavily modified the scoreboard and given it a more original look. I'm marking this as resolved, but if you want a change when you play it. Then obviously you can re-open this with more direct instructions.

**Comment by GingerAdonis** [comment]
Screenshot would be nice

**Comment by Dubyx** [comment]
I'll take a Screenshot of it tonight when I get home and paste the url here.

**Comment by Dubyx** [comment]
http://images.akamai.steamusercontent.com/ugc/262709175062014373/B27BEB412337003F76BD429AB31026A52CF975FC/

**Comment by GingerAdonis** [comment]
Looks better than the original. But still could use some work. Why do you mention 'Ping' and 'SP' on every line? Column headers exist for a reason.

And the position of the mute button doesn't make a lot of sense. Maybe put it directly behind the nickname (not a separate column), or at the beginning/end as a separate column.

The Mr. Green icon doesn't really fit the style. And the title font is meh as well. Why don't you make it only say 'Scoreboard'? Because that's what it is.

**Comment by Dubyx** [comment]
The Ping and SP are mentioned as its to see what other players have compared to you. I gave them these tags so players knew which one was which. Do you feel that its obvious enough to not require these?

Sure ok, I can place the mute button there. It would be more sensible I rekon.

I thought the image looked quite nice as it shows the whole community spirit and all. But if you'd rather can remove it. I can replace it with 'Scoreboard' instead or something. 

Ummm my personal take is. I would like to keep the 'Ping' text. But I can see why you would want to remove the 'SP' and 'Brains' as it makes it look cluttered. Thoughts?

**Comment by GingerAdonis** [comment]
Read again what I said. I was talking about column headers to specify what column is what, instead of putting it on every line/row.

**Comment by Dubyx** [comment]
Ah I see sorry. My brain wasn't working last night. Thus why I didn't do any coding. Yea I see that makes sense. I'll add that and we can see what it looks like. 

I changed the image for the 'scoreboard' text. To my taste it isn't exactly which I like. But if you think it looks good then it doesn't bother me as such. I'll post a picture on Saturday once I've done the other column update.

**Comment by Dubyx** [comment]
It's still a little rough and placement isn't finished, but is this what you wanted to see? 

http://images.akamai.steamusercontent.com/ugc/262709175068668920/775D37D651DD26E28E5C240729E4C3A09DBBA666/

**Comment by Dubyx** [comment]
http://images.akamai.steamusercontent.com/ugc/262709175068678026/5687D92DCB682206DD923ACDDD19450E37249245/

**Comment by Dubyx** [comment]
Fixed*\* http://images.akamai.steamusercontent.com/ugc/262709175068678026/5687D92DCB682206DD923ACDDD19450E37249245/

**Comment by GingerAdonis** [comment]
Yes that's better. Few more suggestions:
- Remove 'Player' and 'Zombie' column headers and add separate "Survivors" and "Zombies" headers to both tables.
- Remove the servername.
- It's "Scoreboard" intead of "ScoreBoard".

**Comment by Dubyx** [comment]
Hows that? :)

http://images.akamai.steamusercontent.com/ugc/262709175068895521/0C4AAE3E8E58D5E9A7F4C8A40BBB98EF3B5A3281/
