### ISSUE TITLE
HUD is odd on 1920x1200

### ISSUE THREAD

**Issue by GingerAdonis** [JarnoVgr/ZombieSurvival#7]
![hl2 2016-02-26 15-39-43-24](https://cloud.githubusercontent.com/assets/2751672/13355239/b14aede4-dc9f-11e5-88de-1aa2d6d2282d.png)
1. Biohazard icon isn't sharp.
2. Several HUD elements are wrongly positioned.

**Comment by Dubyx** [comment]
Ah I see the Ammo part is a little screwy, I'll recode it with the newer system I was using on the different HUD elements.

**Comment by Dubyx** [comment]
Fixed
