### ISSUE TITLE
Missing viewpunches for melee weapons

### ISSUE THREAD

**Issue by GingerAdonis** [JarnoVgr/ZombieSurvival#9]

**Comment by Dubyx** [comment]
View punches?

**Comment by GingerAdonis** [comment]
http://wiki.garrysmod.com/page/Player/ViewPunch

Pushes the screenview when using the melee weapon.

**Comment by Dubyx** [comment]
I'll work this into the Melee base, I've got some code I can re-use for it, so it should only be a short amount of fiddling around. Ummm I'll make it subtle otherwise it will be annoying, for both when a player swings, and hits their target.

**Comment by Dubyx** [comment]
Added, make it subtle as it would be annoying. It looks nice enough and gets the message across that you're swinging something without it being in your face too much.
